### ISSUE TITLE
S2HU-009 Job view [front]

### ISSUE THREAD

**Issue by Argeliosk8** [4GeeksAcademy/latam_tech_jobs#4]
The job view will show all the information regarding the job opening:

Required Columns

-  id
-  title
-  company_name
-  location
-  type
-  job_description
-  experience_level
-  skills
-  languages
-  post_date

**Comment by kitsunemura** [comment]
The job view will show all the information regarding the job opening:
The post model should save the information about the jobs

Required Columns

-  id
-  title
-  company_name
-  location
-  type
-  job_description
-  experience_level
-  skills
-  languages
-  post_date
